In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
## introduction to Tensors

#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
#Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# Matrix
matrix = torch.tensor([[7, 8], 
                      [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
matrix.ndim

2

In [11]:
matrix[0]

tensor([7, 8])

In [12]:
matrix.shape

torch.Size([2, 2])

In [13]:
# Tensor
tensor = torch.tensor([[[1, 2, 3],
                        [1, 1, 1],
                        [2, 3, 4]]])
tensor

tensor([[[1, 2, 3],
         [1, 1, 1],
         [2, 3, 4]]])

In [14]:
tensor.ndim

3

In [15]:
tensor.shape

torch.Size([1, 3, 3])

In [16]:
tensor[0]

tensor([[1, 2, 3],
        [1, 1, 1],
        [2, 3, 4]])

In [17]:
# Random tensors
random_tensor = torch.rand(2, 3, 4)
random_tensor

tensor([[[0.2816, 0.5672, 0.8562, 0.6270],
         [0.7764, 0.5325, 0.7342, 0.6695],
         [0.3375, 0.1191, 0.9145, 0.6313]],

        [[0.7193, 0.3504, 0.7945, 0.5963],
         [0.6929, 0.8283, 0.3765, 0.6727],
         [0.2415, 0.4288, 0.1175, 0.7031]]])

In [18]:
random_tensor.ndim

3

In [19]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=[3, 224, 224]) # high, width, colour channels (RGB)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [20]:
# Zeros and ones tensors
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
zeros*random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [22]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
ones.dtype

torch.float32

In [24]:
random_tensor.dtype

torch.float32

In [25]:
# Create a range of tensors and tensors-like
one_to_ten = torch.arange(1, 11)
one_to_ten


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
a = torch.arange(start=1, end=11, step=1)
a

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
ten_zeroes = torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [28]:
# Tensor datatypes
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                                dtype=None, # datatype of tensor
                                device=None, #for example cuda, rocm etc
                                requires_grad=False) # whether or not to track gradients with tensor operations
float_32_tensor

tensor([3., 6., 9.])

In [29]:
float_32_tensor.dtype

torch.float32

In [30]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [31]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [32]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [33]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.])

In [34]:
# getting info from tensors

some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.5105, 0.4487, 0.5470, 0.1985],
        [0.4050, 0.5858, 0.3648, 0.0511],
        [0.3579, 0.3395, 0.9017, 0.2252]])

In [35]:
print(some_tensor)
print(f'Datatype of tensor: {some_tensor.dtype}')
print(f'Shape of tensor: {some_tensor.shape}')
print(f'Device tensor is on: {some_tensor.device}')

tensor([[0.5105, 0.4487, 0.5470, 0.1985],
        [0.4050, 0.5858, 0.3648, 0.0511],
        [0.3579, 0.3395, 0.9017, 0.2252]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [36]:
# Manipulating tensors
tensor = torch.tensor([1, 2, 3])
tensor + 10


tensor([11, 12, 13])

In [37]:
tensor * 10

tensor([10, 20, 30])

In [38]:
tensor


tensor([1, 2, 3])

In [39]:
tensor - 10

tensor([-9, -8, -7])

In [40]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [41]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [42]:
# matrix multiplication

# element wise 
tensor * tensor

tensor([1, 4, 9])

In [43]:
#matrix 
torch.matmul(tensor, tensor)

tensor(14)

In [44]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.28 ms, sys: 105 μs, total: 1.38 ms
Wall time: 878 μs


In [45]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 163 μs, sys: 0 ns, total: 163 μs
Wall time: 90.1 μs


tensor(14)

In [46]:
# shape errors
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
torch.mm(tensor_A, tensor_B) # mm == matmul

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [ ]:
# use Transpose

tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
#min, max, mean etc
torch.min(tensor), torch.max(tensor)

(tensor(1), tensor(3))

In [ ]:
torch.mean(tensor.type(torch.float32))

tensor(2.)

In [ ]:
torch.sum(tensor)

tensor(6)

In [ ]:
tensor.argmin()

tensor(0)

In [ ]:
tensor.argmax()

tensor(2)

In [ ]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# changing z changes x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
# squeeze and unsqueeze tensors
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_reshaped.shape

torch.Size([1, 9])

In [ ]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x_reshaped.squeeze().shape

torch.Size([9])

In [ ]:
x_squeezed = x_reshaped.squeeze()
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# permute tensors
x_original = torch.rand(size=(224, 224, 3))

x_permuted = x_original.permute(2, 0, 1)

x_original

tensor([[[0.6636, 0.7878, 0.5221],
         [0.8323, 0.5334, 0.5869],
         [0.8736, 0.1404, 0.7693],
         ...,
         [0.7035, 0.1358, 0.9295],
         [0.5323, 0.5757, 0.1225],
         [0.2059, 0.4957, 0.0573]],

        [[0.7117, 0.7787, 0.6136],
         [0.3557, 0.4671, 0.1689],
         [0.0648, 0.6529, 0.4981],
         ...,
         [0.5723, 0.4236, 0.7750],
         [0.5168, 0.9123, 0.3186],
         [0.7868, 0.2999, 0.6014]],

        [[0.2607, 0.3265, 0.8223],
         [0.8754, 0.6772, 0.5074],
         [0.2982, 0.9513, 0.5585],
         ...,
         [0.6509, 0.5368, 0.6057],
         [0.0628, 0.9504, 0.1000],
         [0.2208, 0.2042, 0.4085]],

        ...,

        [[0.8635, 0.7821, 0.7582],
         [0.7210, 0.6238, 0.3896],
         [0.8802, 0.3980, 0.0242],
         ...,
         [0.6300, 0.4683, 0.6290],
         [0.5662, 0.3624, 0.8121],
         [0.8206, 0.5446, 0.9708]],

        [[0.2911, 0.8301, 0.6067],
         [0.5511, 0.4400, 0.1776],
         [0.

In [ ]:
x_permuted

tensor([[[0.6636, 0.8323, 0.8736,  ..., 0.7035, 0.5323, 0.2059],
         [0.7117, 0.3557, 0.0648,  ..., 0.5723, 0.5168, 0.7868],
         [0.2607, 0.8754, 0.2982,  ..., 0.6509, 0.0628, 0.2208],
         ...,
         [0.8635, 0.7210, 0.8802,  ..., 0.6300, 0.5662, 0.8206],
         [0.2911, 0.5511, 0.9746,  ..., 0.9392, 0.6589, 0.3552],
         [0.0908, 0.7331, 0.9244,  ..., 0.3288, 0.4713, 0.5765]],

        [[0.7878, 0.5334, 0.1404,  ..., 0.1358, 0.5757, 0.4957],
         [0.7787, 0.4671, 0.6529,  ..., 0.4236, 0.9123, 0.2999],
         [0.3265, 0.6772, 0.9513,  ..., 0.5368, 0.9504, 0.2042],
         ...,
         [0.7821, 0.6238, 0.3980,  ..., 0.4683, 0.3624, 0.5446],
         [0.8301, 0.4400, 0.9040,  ..., 0.7838, 0.7776, 0.3153],
         [0.4342, 0.2954, 0.3209,  ..., 0.4852, 0.9624, 0.0506]],

        [[0.5221, 0.5869, 0.7693,  ..., 0.9295, 0.1225, 0.0573],
         [0.6136, 0.1689, 0.4981,  ..., 0.7750, 0.3186, 0.6014],
         [0.8223, 0.5074, 0.5585,  ..., 0.6057, 0.1000, 0.

In [ ]:
x_original[0, 0, 0] = 123123
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(123123.), tensor(123123.))

In [ ]:
#indexing
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape



(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# index on x
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][0] # x[0, 0]

tensor([1, 2, 3])

In [ ]:
x[0, 2, 2]

tensor(9)

In [ ]:
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
#NumPy array to tensor

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) #check dtype
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# tensor to numpy

tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# reproducibility
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.8354, 0.0870, 0.6695, 0.2115],
        [0.9399, 0.9648, 0.3615, 0.2526],
        [0.1044, 0.2087, 0.9366, 0.4478]])
tensor([[0.0620, 0.8231, 0.6084, 0.8201],
        [0.2610, 0.2242, 0.6344, 0.5695],
        [0.2923, 0.0081, 0.9867, 0.2587]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)

random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [53]:
# running tensors and pytorch objects on the GPUS

#getting GPU
torch.cuda.is_available()

#ебал амд, пришлось поебаться с rocm и моей рыксой 6600, ну ладно, прощаю

True

In [52]:
# setup device agnostic code

device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [51]:
# Count number of devices
torch.cuda.device_count()

1

In [ ]:
# Putting tensors (and models) on the GPU

tensor = torch.tensor([1, 2, 3], device="cpu")

#tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [49]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [54]:
# move tensor back to the CPU
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [57]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])