In [5]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [6]:
## introduction to Tensors

#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [7]:
scalar.ndim

0

In [8]:
scalar.item()

7

In [9]:
#Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [10]:
vector.ndim

1

In [11]:
vector.shape

torch.Size([2])

In [13]:
# Matrix
matrix = torch.tensor([[7, 8], 
                      [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [14]:
matrix.ndim

2

In [15]:
matrix[0]

tensor([7, 8])

In [16]:
matrix.shape

torch.Size([2, 2])

In [18]:
# Tensor
tensor = torch.tensor([[[1, 2, 3],
                        [1, 1, 1],
                        [2, 3, 4]]])
tensor

tensor([[[1, 2, 3],
         [1, 1, 1],
         [2, 3, 4]]])

In [19]:
tensor.ndim

3

In [20]:
tensor.shape

torch.Size([1, 3, 3])

In [21]:
tensor[0]

tensor([[1, 2, 3],
        [1, 1, 1],
        [2, 3, 4]])

In [24]:
# Random tensors
random_tensor = torch.rand(2, 3, 4)
random_tensor

tensor([[[0.5095, 0.8515, 0.3663, 0.0807],
         [0.3098, 0.1245, 0.6569, 0.4190],
         [0.7702, 0.0872, 0.8528, 0.5273]],

        [[0.4844, 0.4505, 0.5499, 0.0129],
         [0.5818, 0.4445, 0.8250, 0.6373],
         [0.1881, 0.3182, 0.9167, 0.7588]]])

In [25]:
random_tensor.ndim

3

In [28]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=[3, 224, 224]) # high, width, colour channels (RGB)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [30]:
# Zeros and ones tensors
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [31]:
zeros*random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [32]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [33]:
ones.dtype

torch.float32

In [34]:
random_tensor.dtype

torch.float32

In [ ]:
# Create a range of tensors and tensors-like
one_to_ten = torch.arange(1, 11)
one_to_ten


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
a = torch.arange(start=1, end=11, step=1)
a

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
ten_zeroes = torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])