In [5]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [6]:
## introduction to Tensors

#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [7]:
scalar.ndim

0

In [8]:
scalar.item()

7

In [9]:
#Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [10]:
vector.ndim

1

In [11]:
vector.shape

torch.Size([2])

In [13]:
# Matrix
matrix = torch.tensor([[7, 8], 
                      [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [14]:
matrix.ndim

2

In [15]:
matrix[0]

tensor([7, 8])

In [16]:
matrix.shape

torch.Size([2, 2])

In [18]:
# Tensor
tensor = torch.tensor([[[1, 2, 3],
                        [1, 1, 1],
                        [2, 3, 4]]])
tensor

tensor([[[1, 2, 3],
         [1, 1, 1],
         [2, 3, 4]]])

In [19]:
tensor.ndim

3

In [20]:
tensor.shape

torch.Size([1, 3, 3])

In [21]:
tensor[0]

tensor([[1, 2, 3],
        [1, 1, 1],
        [2, 3, 4]])