In [5]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [6]:
## introduction to Tensors

#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [7]:
scalar.ndim

0

In [8]:
scalar.item()

7

In [9]:
#Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [10]:
vector.ndim

1

In [11]:
vector.shape

torch.Size([2])

In [13]:
# Matrix
matrix = torch.tensor([[7, 8], 
                      [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [14]:
matrix.ndim

2

In [15]:
matrix[0]

tensor([7, 8])

In [16]:
matrix.shape

torch.Size([2, 2])

In [18]:
# Tensor
tensor = torch.tensor([[[1, 2, 3],
                        [1, 1, 1],
                        [2, 3, 4]]])
tensor

tensor([[[1, 2, 3],
         [1, 1, 1],
         [2, 3, 4]]])

In [19]:
tensor.ndim

3

In [20]:
tensor.shape

torch.Size([1, 3, 3])

In [21]:
tensor[0]

tensor([[1, 2, 3],
        [1, 1, 1],
        [2, 3, 4]])

In [24]:
# Random tensors
random_tensor = torch.rand(2, 3, 4)
random_tensor

tensor([[[0.5095, 0.8515, 0.3663, 0.0807],
         [0.3098, 0.1245, 0.6569, 0.4190],
         [0.7702, 0.0872, 0.8528, 0.5273]],

        [[0.4844, 0.4505, 0.5499, 0.0129],
         [0.5818, 0.4445, 0.8250, 0.6373],
         [0.1881, 0.3182, 0.9167, 0.7588]]])

In [25]:
random_tensor.ndim

3

In [28]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=[3, 224, 224]) # high, width, colour channels (RGB)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [30]:
# Zeros and ones tensors
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [31]:
zeros*random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [32]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [33]:
ones.dtype

torch.float32

In [34]:
random_tensor.dtype

torch.float32

In [ ]:
# Create a range of tensors and tensors-like
one_to_ten = torch.arange(1, 11)
one_to_ten


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
a = torch.arange(start=1, end=11, step=1)
a

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
ten_zeroes = torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [51]:
# Tensor datatypes
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                                dtype=None, # datatype of tensor
                                device=None, #for example cuda, rocm etc
                                requires_grad=False) # whether or not to track gradients with tensor operations
float_32_tensor

tensor([3., 6., 9.])

In [50]:
float_32_tensor.dtype

torch.float32

In [52]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [53]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [54]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [55]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.])

In [56]:
# getting info from tensors

some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.8922, 0.3348, 0.3698, 0.0620],
        [0.8599, 0.6533, 0.1147, 0.4530],
        [0.2180, 0.9290, 0.5358, 0.6867]])

In [58]:
print(some_tensor)
print(f'Datatype of tensor: {some_tensor.dtype}')
print(f'Shape of tensor: {some_tensor.shape}')
print(f'Device tensor is on: {some_tensor.device}')

tensor([[0.8922, 0.3348, 0.3698, 0.0620],
        [0.8599, 0.6533, 0.1147, 0.4530],
        [0.2180, 0.9290, 0.5358, 0.6867]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [63]:
# Manipulating tensors
tensor = torch.tensor([1, 2, 3])
tensor + 10


tensor([11, 12, 13])

In [64]:
tensor * 10

tensor([10, 20, 30])

In [65]:
tensor


tensor([1, 2, 3])

In [66]:
tensor - 10

tensor([-9, -8, -7])

In [67]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [68]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [69]:
# matrix multiplication

# element wise 
tensor * tensor

tensor([1, 4, 9])

In [70]:
#matrix 
torch.matmul(tensor, tensor)

tensor(14)

In [73]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 902 μs, sys: 0 ns, total: 902 μs
Wall time: 581 μs


In [82]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 363 μs, sys: 22 μs, total: 385 μs
Wall time: 306 μs


tensor(14)

In [83]:
# shape errors
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
torch.mm(tensor_A, tensor_B) # mm == matmul

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [84]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [85]:
# use Transpose

tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [88]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [90]:
#min, max, mean etc
torch.min(tensor), torch.max(tensor)

(tensor(1), tensor(3))

In [92]:
torch.mean(tensor.type(torch.float32))

tensor(2.)

In [96]:
torch.sum(tensor)

tensor(6)

In [109]:
tensor.argmin()

tensor(0)

In [110]:
tensor.argmax()

tensor(2)